/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorldApp */

#ifndef _Included_HelloWorldApp
#define _Included_HelloWorldApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorldApp
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldApp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
